create table if not exists public.atendimento_pendencias (
  id bigint generated by default as identity primary key,
  atendimento_id bigint not null references public.atendimentos(id) on delete cascade,
  pendencia_id bigint not null references public.pendencias_ordem(id) on delete restrict,
  status text not null check (status in ('Aberta', 'Pendente', 'Concluida')),
  observacao text not null default '',
  created_at timestamptz not null default now(),
  unique (atendimento_id, pendencia_id)
);

create index if not exists idx_atendimento_pendencias_atendimento_id
  on public.atendimento_pendencias(atendimento_id);
create index if not exists idx_atendimento_pendencias_pendencia_id
  on public.atendimento_pendencias(pendencia_id);

alter table public.atendimento_pendencias enable row level security;

drop policy if exists "atendimento_pendencias_select_autenticado" on public.atendimento_pendencias;
create policy "atendimento_pendencias_select_autenticado"
on public.atendimento_pendencias for select
to authenticated
using (private.has_active_profile((select auth.uid())));

create or replace function public.registrar_atendimento_com_materiais(
  p_ordem_id integer,
  p_data date,
  p_status text,
  p_equipe text,
  p_relato text,
  p_materiais jsonb default '[]'::jsonb,
  p_pendencias jsonb default '[]'::jsonb
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  created_atendimento_id integer;
  created_movimentacao_id integer;
  item jsonb;
  item_id_material integer;
  item_quantidade numeric;
  item_tipo_uso text;
  item_observacao text;
  item_descricao text;
  pendencia jsonb;
  pendencia_id bigint;
  pendencia_status text;
  pendencia_observacao text;
  total_pendencias integer;
  concluidas integer;
  acompanhadas integer;
begin
  if not private.has_active_profile((select auth.uid())) then
    raise exception 'Usuario sem perfil ativo';
  end if;

  if p_ordem_id is null then
    raise exception 'OS obrigatoria';
  end if;

  if p_status not in ('Executado', 'Parcial', 'Reagendado') then
    raise exception 'Status de atendimento invalido';
  end if;

  if jsonb_typeof(coalesce(p_materiais, '[]'::jsonb)) <> 'array' then
    raise exception 'Materiais devem ser enviados como lista';
  end if;

  if jsonb_typeof(coalesce(p_pendencias, '[]'::jsonb)) <> 'array' then
    raise exception 'Pendencias devem ser enviadas como lista';
  end if;

  insert into public.atendimentos (
    ordem_id,
    data,
    equipe,
    status,
    relato
  )
  values (
    p_ordem_id,
    coalesce(p_data, current_date),
    coalesce(nullif(trim(p_equipe), ''), 'Equipe interna'),
    coalesce(nullif(trim(p_status), ''), 'Executado'),
    coalesce(trim(p_relato), '')
  )
  returning id into created_atendimento_id;

  for pendencia in select * from jsonb_array_elements(coalesce(p_pendencias, '[]'::jsonb))
  loop
    pendencia_id := nullif(pendencia->>'idPendencia', '')::bigint;
    pendencia_status := coalesce(nullif(trim(pendencia->>'status'), ''), 'Pendente');
    pendencia_observacao := coalesce(trim(pendencia->>'observacao'), '');

    if pendencia_id is null then
      raise exception 'Pendencia obrigatoria em todas as linhas';
    end if;

    if pendencia_status not in ('Aberta', 'Pendente', 'Concluida') then
      raise exception 'Status de pendencia invalido';
    end if;

    if not exists (
      select 1
      from public.pendencias_ordem po
      where po.id = pendencia_id
        and po.ordem_id = p_ordem_id
    ) then
      raise exception 'Pendencia nao pertence a OS informada';
    end if;

    insert into public.atendimento_pendencias (
      atendimento_id,
      pendencia_id,
      status,
      observacao
    )
    values (
      created_atendimento_id,
      pendencia_id,
      pendencia_status,
      pendencia_observacao
    )
    on conflict (atendimento_id, pendencia_id) do update
    set
      status = excluded.status,
      observacao = excluded.observacao;

    update public.pendencias_ordem
    set status = pendencia_status
    where id = pendencia_id;
  end loop;

  for item in select * from jsonb_array_elements(coalesce(p_materiais, '[]'::jsonb))
  loop
    item_id_material := nullif(item->>'idMaterial', '')::integer;
    item_quantidade := nullif(item->>'quantidade', '')::numeric;
    item_tipo_uso := coalesce(nullif(trim(item->>'tipoUso'), ''), 'consumo');
    item_observacao := coalesce(trim(item->>'observacao'), '');

    if item_id_material is null then
      raise exception 'Material obrigatorio em todas as linhas';
    end if;

    if item_quantidade is null or item_quantidade <= 0 then
      raise exception 'Quantidade deve ser maior que zero em todas as linhas';
    end if;

    if item_tipo_uso not in ('consumo', 'emprestimo_ferramenta', 'perda_avaria') then
      raise exception 'Tipo de uso de material invalido';
    end if;

    select descricao
    into item_descricao
    from public.estoque_materiais
    where id_material = item_id_material
      and ativo is true;

    if item_descricao is null then
      raise exception 'Material inexistente ou inativo';
    end if;

    insert into public.atendimento_materiais (
      atendimento_id,
      descricao
    )
    values (
      created_atendimento_id,
      concat(
        item_descricao,
        ' | qtd: ',
        item_quantidade,
        ' | uso: ',
        case item_tipo_uso
          when 'consumo' then 'consumo'
          when 'emprestimo_ferramenta' then 'emprestimo de ferramenta/equipamento'
          when 'perda_avaria' then 'perda ou avaria'
        end,
        case when item_observacao <> '' then concat(' | obs: ', item_observacao) else '' end
      )
    );

    insert into public.movimentacoes (
      data_movimentacao,
      tipo_codigo,
      origem,
      observacao,
      criado_por
    )
    values (
      coalesce(p_data::timestamptz, now()),
      'saida',
      concat('Atendimento MVP #', created_atendimento_id),
      concat(
        case item_tipo_uso
          when 'consumo' then 'Consumo em atendimento'
          when 'emprestimo_ferramenta' then 'Emprestimo de ferramenta/equipamento para equipe'
          when 'perda_avaria' then 'Perda ou avaria em atendimento'
        end,
        case when item_observacao <> '' then concat(': ', item_observacao) else '' end
      ),
      (select auth.uid())
    )
    returning id_movimentacao into created_movimentacao_id;

    insert into public.movimentacoes_estoque (
      id_movimentacao,
      id_material,
      quantidade
    )
    values (
      created_movimentacao_id,
      item_id_material,
      item_quantidade
    );
  end loop;

  select
    count(*),
    count(*) filter (where status = 'Concluida'),
    count(*) filter (where status <> 'Aberta')
  into total_pendencias, concluidas, acompanhadas
  from public.pendencias_ordem
  where ordem_id = p_ordem_id;

  update public.ordens
  set status = case
    when total_pendencias > 0 and concluidas = total_pendencias then 'Concluida'
    when acompanhadas > 0 or p_status in ('Parcial', 'Reagendado') then 'Pendente'
    when p_status = 'Executado' and total_pendencias = 0 then 'Concluida'
    else 'Em atendimento'
  end
  where id = p_ordem_id;

  return created_atendimento_id;
end;
$$;

revoke execute on function public.registrar_atendimento_com_materiais(integer, date, text, text, text, jsonb, jsonb)
  from public, anon;
grant execute on function public.registrar_atendimento_com_materiais(integer, date, text, text, text, jsonb, jsonb)
  to authenticated;

comment on function public.registrar_atendimento_com_materiais(integer, date, text, text, text, jsonb, jsonb)
  is 'Registra atendimento MVP, acompanhamento de pendencias e materiais estruturados em transacao unica, gerando saidas canonicas de estoque por consumo, emprestimo de ferramenta/equipamento ou perda/avaria.';
