-- Phase 1 canonical maintenance schema, business rules and RLS.
-- The previous MVP tables remain in place for compatibility until Phase 2
-- migrates the frontend to these canonical tables.

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'perfis'
      and column_name = 'user_id'
  ) then
    alter table public.perfis rename column user_id to id;
  end if;
end $$;

create schema if not exists private;

create or replace function private.has_active_profile(target_user_id uuid)
returns boolean
language sql
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.perfis
    where id = target_user_id
      and ativo is true
  );
$$;

create or replace function private.is_gestor(target_user_id uuid)
returns boolean
language sql
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.perfis
    where id = target_user_id
      and perfil = 'gestor'
      and ativo is true
  );
$$;

create or replace function private.current_id_colaborador()
returns integer
language sql
security definer
set search_path = ''
as $$
  select id_colaborador
  from public.perfis
  where id = auth.uid()
    and ativo is true;
$$;

create or replace function private.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.perfis (id, nome, perfil)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nome', new.email, ''),
    'tecnico'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

alter table public.perfis
  add column if not exists id_colaborador integer,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.status_contrato (
  codigo text primary key,
  descricao text not null,
  ordem integer not null default 0,
  ativo boolean not null default true
);

create table if not exists public.status_unidade (
  codigo text primary key,
  descricao text not null,
  ordem integer not null default 0,
  ativo boolean not null default true
);

create table if not exists public.status_ordem (
  codigo text primary key,
  descricao text not null,
  ordem integer not null default 0,
  ativo boolean not null default true
);

create table if not exists public.status_atendimento (
  codigo text primary key,
  descricao text not null,
  ordem integer not null default 0,
  ativo boolean not null default true
);

create table if not exists public.status_pendencia (
  codigo text primary key,
  descricao text not null,
  ordem integer not null default 0,
  ativo boolean not null default true
);

create table if not exists public.tipos_movimentacao (
  codigo text primary key,
  descricao text not null,
  fator integer not null check (fator in (-1, 1)),
  ativo boolean not null default true
);

insert into public.status_contrato (codigo, descricao, ordem) values
  ('ativo', 'Ativo', 10),
  ('suspenso', 'Suspenso', 20),
  ('encerrado', 'Encerrado', 30),
  ('cancelado', 'Cancelado', 40)
on conflict (codigo) do update set descricao = excluded.descricao, ordem = excluded.ordem;

insert into public.status_unidade (codigo, descricao, ordem) values
  ('instalada', 'Instalada', 10),
  ('em_manutencao', 'Em manutencao', 20),
  ('desmobilizada', 'Desmobilizada', 30),
  ('inativa', 'Inativa', 40)
on conflict (codigo) do update set descricao = excluded.descricao, ordem = excluded.ordem;

insert into public.status_ordem (codigo, descricao, ordem) values
  ('aberta', 'Aberta', 10),
  ('em_andamento', 'Em andamento', 20),
  ('concluida', 'Concluida', 30),
  ('cancelada', 'Cancelada', 40)
on conflict (codigo) do update set descricao = excluded.descricao, ordem = excluded.ordem;

insert into public.status_atendimento (codigo, descricao, ordem) values
  ('aberto', 'Aberto', 10),
  ('em_execucao', 'Em execucao', 20),
  ('concluido', 'Concluido', 30),
  ('cancelado', 'Cancelado', 40)
on conflict (codigo) do update set descricao = excluded.descricao, ordem = excluded.ordem;

insert into public.status_pendencia (codigo, descricao, ordem) values
  ('aberta', 'Aberta', 10),
  ('em_tratamento', 'Em tratamento', 20),
  ('concluida', 'Concluida', 30),
  ('cancelada', 'Cancelada', 40)
on conflict (codigo) do update set descricao = excluded.descricao, ordem = excluded.ordem;

insert into public.tipos_movimentacao (codigo, descricao, fator) values
  ('entrada', 'Entrada', 1),
  ('saida', 'Saida', -1),
  ('ajuste', 'Ajuste manual', 1)
on conflict (codigo) do update set descricao = excluded.descricao, fator = excluded.fator;

create table if not exists public.clientes (
  id_cliente integer generated by default as identity primary key,
  nome text not null,
  documento text,
  email text,
  telefone text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.empresas (
  id_empresa integer generated by default as identity primary key,
  razao_social text not null,
  nome_fantasia text,
  cnpj text not null unique,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.contratos (
  id_contrato integer generated by default as identity primary key,
  id_cliente integer not null references public.clientes(id_cliente) on delete restrict,
  id_empresa integer not null references public.empresas(id_empresa) on delete restrict,
  numero_contrato text not null unique,
  objeto text not null default '',
  status_codigo text not null references public.status_contrato(codigo) on delete restrict default 'ativo',
  data_inicio date,
  data_fim date,
  valor_total numeric(12,2),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.projetos (
  id_projeto integer generated by default as identity primary key,
  id_contrato integer not null references public.contratos(id_contrato) on delete restrict,
  nome text not null,
  municipio text not null default '',
  uf text not null default '',
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.unidades_instaladas (
  id_unidade integer generated by default as identity primary key,
  id_projeto integer not null references public.projetos(id_projeto) on delete restrict,
  codigo text not null unique,
  nome text not null,
  status_codigo text not null references public.status_unidade(codigo) on delete restrict default 'instalada',
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.colaboradores (
  id_colaborador integer generated by default as identity primary key,
  nome text not null,
  cargo text,
  email text,
  telefone text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.terceirizados (
  id_terceira integer generated by default as identity primary key,
  nome text not null,
  empresa text,
  documento text,
  telefone text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table public.perfis
  drop constraint if exists perfis_id_colaborador_fkey,
  add constraint perfis_id_colaborador_fkey
    foreign key (id_colaborador) references public.colaboradores(id_colaborador) on delete restrict;

create table if not exists public.estoque_materiais (
  id_material integer generated by default as identity primary key,
  codigo text unique,
  descricao text not null,
  categoria text not null default '',
  unidade_medida text not null default 'un',
  estoque_minimo numeric(12,2) not null default 0,
  estoque_atual numeric(12,2) not null default 0,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.pendencias_padrao (
  id_pendencia integer generated by default as identity primary key,
  codigo text unique,
  descricao text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.ordens_manutencao (
  id_ordem integer generated by default as identity primary key,
  id_unidade integer not null references public.unidades_instaladas(id_unidade) on delete restrict,
  protocolo text not null unique,
  tipo text not null default 'corretiva',
  prioridade text not null default 'P3' check (prioridade in ('P1', 'P2', 'P3', 'P4')),
  status_codigo text not null references public.status_ordem(codigo) on delete restrict default 'aberta',
  abertura_em timestamptz not null default now(),
  prazo_sla timestamptz,
  data_conclusao timestamptz,
  descricao text not null default '',
  criado_por uuid references public.perfis(id) on delete restrict,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.pendencias_ordem_manutencao (
  id_pendencia_ordem integer generated by default as identity primary key,
  id_ordem integer not null references public.ordens_manutencao(id_ordem) on delete restrict,
  id_pendencia integer not null references public.pendencias_padrao(id_pendencia) on delete restrict,
  status_codigo text not null references public.status_pendencia(codigo) on delete restrict default 'aberta',
  descricao_snapshot text not null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (id_ordem, id_pendencia)
);

create table if not exists public.atendimentos_ordens (
  id_atendimento integer generated by default as identity primary key,
  id_ordem integer not null references public.ordens_manutencao(id_ordem) on delete restrict,
  status_codigo text not null references public.status_atendimento(codigo) on delete restrict default 'aberto',
  data_abertura timestamptz not null default now(),
  data_fechamento timestamptz,
  relato text not null default '',
  criado_por uuid not null references public.perfis(id) on delete restrict default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.equipes (
  id_equipe integer generated by default as identity primary key,
  id_atendimento integer not null references public.atendimentos_ordens(id_atendimento) on delete restrict,
  id_colaborador integer references public.colaboradores(id_colaborador) on delete restrict,
  id_terceira integer references public.terceirizados(id_terceira) on delete restrict,
  funcao text,
  criado_por uuid not null references public.perfis(id) on delete restrict default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint equipes_um_membro_check check (
    (id_colaborador is not null and id_terceira is null)
    or (id_colaborador is null and id_terceira is not null)
  )
);

create table if not exists public.atendimentos_executados (
  id_execucao integer generated by default as identity primary key,
  id_atendimento integer not null references public.atendimentos_ordens(id_atendimento) on delete restrict,
  id_pendencia_ordem integer not null references public.pendencias_ordem_manutencao(id_pendencia_ordem) on delete restrict,
  status_codigo text not null references public.status_pendencia(codigo) on delete restrict default 'aberta',
  observacao text not null default '',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (id_atendimento, id_pendencia_ordem)
);

create table if not exists public.movimentacoes (
  id_movimentacao integer generated by default as identity primary key,
  data_movimentacao timestamptz not null default now(),
  tipo_codigo text not null references public.tipos_movimentacao(codigo) on delete restrict,
  origem text not null default '',
  observacao text not null default '',
  criado_por uuid not null references public.perfis(id) on delete restrict default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.movimentacoes_estoque (
  id_movimentacao_estoque integer generated by default as identity primary key,
  id_movimentacao integer not null references public.movimentacoes(id_movimentacao) on delete restrict,
  id_material integer not null references public.estoque_materiais(id_material) on delete restrict,
  id_atendimento integer references public.atendimentos_ordens(id_atendimento) on delete restrict,
  quantidade numeric(12,2) not null check (quantidade <> 0),
  criado_em timestamptz not null default now()
);

create table if not exists public.historico_unidade (
  id_historico integer generated by default as identity primary key,
  id_unidade integer not null references public.unidades_instaladas(id_unidade) on delete restrict,
  descricao text not null,
  registrado_em timestamptz not null default now()
);

create table if not exists public.notificacoes (
  id_notificacao integer generated by default as identity primary key,
  id_ordem integer references public.ordens_manutencao(id_ordem) on delete restrict,
  data_recebimento timestamptz not null default now(),
  assunto text not null default '',
  conteudo text not null default ''
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.set_atualizado_em()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

create or replace function private.ensure_ordem_contrato_ativo()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.unidades_instaladas ui
    join public.projetos p on p.id_projeto = ui.id_projeto
    join public.contratos c on c.id_contrato = p.id_contrato
    where ui.id_unidade = new.id_unidade
      and ui.ativo is true
      and p.ativo is true
      and c.ativo is true
      and c.status_codigo = 'ativo'
  ) then
    raise exception 'OS so pode ser criada para unidade vinculada a contrato ativo';
  end if;

  new.criado_por = coalesce(new.criado_por, auth.uid());
  return new;
end;
$$;

create or replace function private.load_pendencias_atendimento()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.atendimentos_executados (id_atendimento, id_pendencia_ordem, status_codigo)
  select new.id_atendimento, pom.id_pendencia_ordem, 'aberta'
  from public.pendencias_ordem_manutencao pom
  where pom.id_ordem = new.id_ordem
    and pom.status_codigo <> 'concluida'
  on conflict (id_atendimento, id_pendencia_ordem) do nothing;

  return new;
end;
$$;

create or replace function private.recalcular_status_ordem(target_id_ordem integer)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  total_pendencias integer;
  concluidas integer;
  tratadas integer;
  next_status text;
begin
  select
    count(*),
    count(*) filter (where pom.status_codigo = 'concluida'),
    count(*) filter (
      where pom.status_codigo = 'concluida'
         or exists (
           select 1
           from public.atendimentos_executados ae
           where ae.id_pendencia_ordem = pom.id_pendencia_ordem
             and ae.status_codigo <> 'aberta'
         )
    )
  into total_pendencias, concluidas, tratadas
  from public.pendencias_ordem_manutencao pom
  where pom.id_ordem = target_id_ordem;

  if total_pendencias > 0 and concluidas = total_pendencias then
    next_status := 'concluida';
  elsif tratadas > 0 then
    next_status := 'em_andamento';
  else
    next_status := 'aberta';
  end if;

  update public.ordens_manutencao
  set status_codigo = next_status,
      data_conclusao = case
        when next_status = 'concluida' then coalesce(data_conclusao, now())
        else null
      end,
      atualizado_em = now()
  where id_ordem = target_id_ordem
    and status_codigo <> 'cancelada';
end;
$$;

create or replace function private.recalcular_status_ordem_trigger()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id integer;
begin
  if tg_table_name = 'pendencias_ordem_manutencao' then
    target_id := coalesce(new.id_ordem, old.id_ordem);
  else
    select pom.id_ordem
    into target_id
    from public.pendencias_ordem_manutencao pom
    where pom.id_pendencia_ordem = coalesce(new.id_pendencia_ordem, old.id_pendencia_ordem);
  end if;

  perform private.recalcular_status_ordem(target_id);
  return coalesce(new, old);
end;
$$;

create or replace function private.sync_pendencia_status_from_execucao()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status_codigo = 'concluida' then
    update public.pendencias_ordem_manutencao
    set status_codigo = 'concluida',
        atualizado_em = now()
    where id_pendencia_ordem = new.id_pendencia_ordem;
  elsif new.status_codigo = 'em_tratamento' then
    update public.pendencias_ordem_manutencao
    set status_codigo = 'em_tratamento',
        atualizado_em = now()
    where id_pendencia_ordem = new.id_pendencia_ordem
      and status_codigo <> 'concluida';
  end if;

  return new;
end;
$$;

create or replace function private.recalcular_estoque_material(target_id_material integer)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.estoque_materiais em
  set estoque_atual = coalesce((
        select sum(me.quantidade * tm.fator)
        from public.movimentacoes_estoque me
        join public.movimentacoes m on m.id_movimentacao = me.id_movimentacao
        join public.tipos_movimentacao tm on tm.codigo = m.tipo_codigo
        where me.id_material = target_id_material
      ), 0),
      atualizado_em = now()
  where em.id_material = target_id_material;
$$;

create or replace function private.recalcular_estoque_trigger()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.recalcular_estoque_material(coalesce(new.id_material, old.id_material));
  return coalesce(new, old);
end;
$$;

create or replace function public.criar_ordem_manutencao(
  p_id_unidade integer,
  p_protocolo text,
  p_tipo text,
  p_prioridade text,
  p_prazo_sla timestamptz,
  p_descricao text,
  p_pendencias integer[]
)
returns public.ordens_manutencao
language plpgsql
security invoker
set search_path = ''
as $$
declare
  created_order public.ordens_manutencao;
begin
  insert into public.ordens_manutencao (
    id_unidade,
    protocolo,
    tipo,
    prioridade,
    prazo_sla,
    descricao,
    criado_por
  )
  values (
    p_id_unidade,
    p_protocolo,
    coalesce(nullif(p_tipo, ''), 'corretiva'),
    coalesce(nullif(p_prioridade, ''), 'P3'),
    p_prazo_sla,
    coalesce(p_descricao, ''),
    auth.uid()
  )
  returning * into created_order;

  insert into public.pendencias_ordem_manutencao (
    id_ordem,
    id_pendencia,
    status_codigo,
    descricao_snapshot
  )
  select
    created_order.id_ordem,
    pp.id_pendencia,
    'aberta',
    pp.descricao
  from public.pendencias_padrao pp
  where pp.id_pendencia = any(coalesce(p_pendencias, '{}'))
    and pp.ativo is true
  on conflict (id_ordem, id_pendencia) do nothing;

  select *
  into created_order
  from public.ordens_manutencao
  where id_ordem = created_order.id_ordem;

  return created_order;
end;
$$;

drop trigger if exists set_perfis_updated_at on public.perfis;
create trigger set_perfis_updated_at
before update on public.perfis
for each row execute function public.set_updated_at();

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'clientes', 'empresas', 'contratos', 'projetos', 'unidades_instaladas',
    'colaboradores', 'terceirizados', 'estoque_materiais', 'pendencias_padrao',
    'ordens_manutencao', 'pendencias_ordem_manutencao', 'atendimentos_ordens',
    'equipes', 'atendimentos_executados', 'movimentacoes'
  ] loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_atualizado_em()',
      table_name,
      table_name
    );
  end loop;
end $$;

drop trigger if exists ensure_ordem_contrato_ativo on public.ordens_manutencao;
create trigger ensure_ordem_contrato_ativo
before insert or update of id_unidade on public.ordens_manutencao
for each row execute function private.ensure_ordem_contrato_ativo();

drop trigger if exists load_pendencias_atendimento on public.atendimentos_ordens;
create trigger load_pendencias_atendimento
after insert on public.atendimentos_ordens
for each row execute function private.load_pendencias_atendimento();

drop trigger if exists recalc_ordem_from_pendencia on public.pendencias_ordem_manutencao;
create trigger recalc_ordem_from_pendencia
after insert or update or delete on public.pendencias_ordem_manutencao
for each row execute function private.recalcular_status_ordem_trigger();

drop trigger if exists sync_pendencia_from_execucao on public.atendimentos_executados;
create trigger sync_pendencia_from_execucao
after insert or update of status_codigo on public.atendimentos_executados
for each row execute function private.sync_pendencia_status_from_execucao();

drop trigger if exists recalc_ordem_from_execucao on public.atendimentos_executados;
create trigger recalc_ordem_from_execucao
after insert or update or delete on public.atendimentos_executados
for each row execute function private.recalcular_status_ordem_trigger();

drop trigger if exists recalc_estoque_material on public.movimentacoes_estoque;
create trigger recalc_estoque_material
after insert or update or delete on public.movimentacoes_estoque
for each row execute function private.recalcular_estoque_trigger();

create index if not exists idx_perfis_id_colaborador on public.perfis(id_colaborador);
create index if not exists idx_contratos_id_cliente on public.contratos(id_cliente);
create index if not exists idx_contratos_id_empresa on public.contratos(id_empresa);
create index if not exists idx_contratos_status_codigo on public.contratos(status_codigo);
create index if not exists idx_projetos_id_contrato on public.projetos(id_contrato);
create index if not exists idx_unidades_instaladas_id_projeto on public.unidades_instaladas(id_projeto);
create index if not exists idx_unidades_instaladas_status_codigo on public.unidades_instaladas(status_codigo);
create index if not exists idx_ordens_manutencao_id_unidade on public.ordens_manutencao(id_unidade);
create index if not exists idx_ordens_manutencao_criado_por on public.ordens_manutencao(criado_por);
create index if not exists idx_ordens_manutencao_status_codigo on public.ordens_manutencao(status_codigo);
create index if not exists idx_pendencias_ordem_manutencao_id_ordem on public.pendencias_ordem_manutencao(id_ordem);
create index if not exists idx_pendencias_ordem_manutencao_id_pendencia on public.pendencias_ordem_manutencao(id_pendencia);
create index if not exists idx_pendencias_ordem_manutencao_status_codigo on public.pendencias_ordem_manutencao(status_codigo);
create index if not exists idx_atendimentos_ordens_id_ordem on public.atendimentos_ordens(id_ordem);
create index if not exists idx_atendimentos_ordens_criado_por on public.atendimentos_ordens(criado_por);
create index if not exists idx_atendimentos_ordens_status_codigo on public.atendimentos_ordens(status_codigo);
create index if not exists idx_equipes_id_atendimento on public.equipes(id_atendimento);
create index if not exists idx_equipes_id_colaborador on public.equipes(id_colaborador);
create index if not exists idx_equipes_id_terceira on public.equipes(id_terceira);
create index if not exists idx_equipes_criado_por on public.equipes(criado_por);
create index if not exists idx_atendimentos_executados_id_atendimento on public.atendimentos_executados(id_atendimento);
create index if not exists idx_atendimentos_executados_id_pendencia_ordem on public.atendimentos_executados(id_pendencia_ordem);
create index if not exists idx_atendimentos_executados_status_codigo on public.atendimentos_executados(status_codigo);
create index if not exists idx_movimentacoes_criado_por on public.movimentacoes(criado_por);
create index if not exists idx_movimentacoes_tipo_codigo on public.movimentacoes(tipo_codigo);
create index if not exists idx_movimentacoes_estoque_id_movimentacao on public.movimentacoes_estoque(id_movimentacao);
create index if not exists idx_movimentacoes_estoque_id_material on public.movimentacoes_estoque(id_material);
create index if not exists idx_movimentacoes_estoque_id_atendimento on public.movimentacoes_estoque(id_atendimento);
create index if not exists idx_historico_unidade_id_unidade on public.historico_unidade(id_unidade);
create index if not exists idx_notificacoes_id_ordem on public.notificacoes(id_ordem);

create or replace view public.vw_atendimentos_por_projeto
with (security_invoker = true)
as
select
  c.id_contrato,
  c.numero_contrato,
  pr.id_projeto,
  pr.nome as projeto_nome,
  ui.id_unidade,
  ui.codigo as unidade_codigo,
  om.id_ordem,
  om.protocolo,
  ao.id_atendimento,
  ao.status_codigo as status_atendimento,
  ao.data_abertura,
  em.id_material,
  em.descricao as material_descricao,
  me.quantidade as material_quantidade,
  col.id_colaborador,
  col.nome as colaborador_nome,
  ter.id_terceira,
  ter.nome as terceirizado_nome
from public.atendimentos_ordens ao
join public.ordens_manutencao om on om.id_ordem = ao.id_ordem
join public.unidades_instaladas ui on ui.id_unidade = om.id_unidade
join public.projetos pr on pr.id_projeto = ui.id_projeto
join public.contratos c on c.id_contrato = pr.id_contrato
left join public.movimentacoes_estoque me on me.id_atendimento = ao.id_atendimento
left join public.estoque_materiais em on em.id_material = me.id_material
left join public.equipes eq on eq.id_atendimento = ao.id_atendimento
left join public.colaboradores col on col.id_colaborador = eq.id_colaborador
left join public.terceirizados ter on ter.id_terceira = eq.id_terceira
where private.is_gestor((select auth.uid()));

alter table public.status_contrato enable row level security;
alter table public.status_unidade enable row level security;
alter table public.status_ordem enable row level security;
alter table public.status_atendimento enable row level security;
alter table public.status_pendencia enable row level security;
alter table public.tipos_movimentacao enable row level security;
alter table public.clientes enable row level security;
alter table public.empresas enable row level security;
alter table public.contratos enable row level security;
alter table public.projetos enable row level security;
alter table public.unidades_instaladas enable row level security;
alter table public.colaboradores enable row level security;
alter table public.terceirizados enable row level security;
alter table public.estoque_materiais enable row level security;
alter table public.pendencias_padrao enable row level security;
alter table public.ordens_manutencao enable row level security;
alter table public.pendencias_ordem_manutencao enable row level security;
alter table public.atendimentos_ordens enable row level security;
alter table public.equipes enable row level security;
alter table public.atendimentos_executados enable row level security;
alter table public.movimentacoes enable row level security;
alter table public.movimentacoes_estoque enable row level security;
alter table public.historico_unidade enable row level security;
alter table public.notificacoes enable row level security;

revoke all on table
  public.status_contrato,
  public.status_unidade,
  public.status_ordem,
  public.status_atendimento,
  public.status_pendencia,
  public.tipos_movimentacao,
  public.clientes,
  public.empresas,
  public.contratos,
  public.projetos,
  public.unidades_instaladas,
  public.colaboradores,
  public.terceirizados,
  public.estoque_materiais,
  public.pendencias_padrao,
  public.ordens_manutencao,
  public.pendencias_ordem_manutencao,
  public.atendimentos_ordens,
  public.equipes,
  public.atendimentos_executados,
  public.movimentacoes,
  public.movimentacoes_estoque,
  public.historico_unidade,
  public.notificacoes,
  public.vw_atendimentos_por_projeto
from anon, authenticated;

grant select on table
  public.status_contrato,
  public.status_unidade,
  public.status_ordem,
  public.status_atendimento,
  public.status_pendencia,
  public.tipos_movimentacao,
  public.clientes,
  public.empresas,
  public.contratos,
  public.projetos,
  public.unidades_instaladas,
  public.colaboradores,
  public.terceirizados,
  public.estoque_materiais,
  public.pendencias_padrao,
  public.ordens_manutencao,
  public.pendencias_ordem_manutencao,
  public.atendimentos_ordens,
  public.equipes,
  public.atendimentos_executados,
  public.movimentacoes,
  public.movimentacoes_estoque,
  public.vw_atendimentos_por_projeto
to authenticated;

grant insert, update on table
  public.clientes,
  public.empresas,
  public.contratos,
  public.projetos,
  public.unidades_instaladas,
  public.colaboradores,
  public.terceirizados,
  public.estoque_materiais,
  public.pendencias_padrao
to authenticated;

grant insert on table
  public.ordens_manutencao,
  public.pendencias_ordem_manutencao,
  public.atendimentos_ordens,
  public.equipes,
  public.atendimentos_executados,
  public.movimentacoes,
  public.movimentacoes_estoque
to authenticated;

grant update on table
  public.ordens_manutencao,
  public.atendimentos_ordens,
  public.equipes,
  public.atendimentos_executados,
  public.movimentacoes,
  public.movimentacoes_estoque
to authenticated;

grant select, insert, update on table public.perfis to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.criar_ordem_manutencao(integer, text, text, text, timestamptz, text, integer[]) to authenticated;

revoke execute on function private.has_active_profile(uuid) from public;
revoke execute on function private.is_gestor(uuid) from public;
revoke execute on function private.current_id_colaborador() from public;
revoke execute on function private.handle_new_user_profile() from public;
revoke execute on function private.ensure_ordem_contrato_ativo() from public;
revoke execute on function private.load_pendencias_atendimento() from public;
revoke execute on function private.recalcular_status_ordem(integer) from public;
revoke execute on function private.recalcular_status_ordem_trigger() from public;
revoke execute on function private.sync_pendencia_status_from_execucao() from public;
revoke execute on function private.recalcular_estoque_material(integer) from public;
revoke execute on function private.recalcular_estoque_trigger() from public;
revoke execute on function public.set_updated_at() from public;
revoke execute on function public.set_atualizado_em() from public;
grant execute on function private.has_active_profile(uuid) to authenticated;
grant execute on function private.is_gestor(uuid) to authenticated;
grant execute on function private.current_id_colaborador() to authenticated;

drop policy if exists "authenticated read own profile" on public.perfis;
create policy "authenticated read own profile"
on public.perfis for select
to authenticated
using (
  id = (select auth.uid())
  or private.is_gestor((select auth.uid()))
);
comment on policy "authenticated read own profile" on public.perfis
  is 'Usuarios autenticados leem apenas o proprio perfil; gestor pode consultar perfis para administracao.';

drop policy if exists "authenticated update own profile name" on public.perfis;

drop policy if exists "gestores create perfis" on public.perfis;
create policy "gestores create perfis"
on public.perfis for insert
to authenticated
with check (private.is_gestor((select auth.uid())));
comment on policy "gestores create perfis" on public.perfis
  is 'Apenas gestor cria perfis de usuario.';

drop policy if exists "gestores update perfis" on public.perfis;
create policy "gestores update perfis"
on public.perfis for update
to authenticated
using (private.is_gestor((select auth.uid())))
with check (private.is_gestor((select auth.uid())));
comment on policy "gestores update perfis" on public.perfis
  is 'Apenas gestor altera perfil, colaborador vinculado e status ativo de usuarios.';

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'status_contrato', 'status_unidade', 'status_ordem', 'status_atendimento',
    'status_pendencia', 'tipos_movimentacao'
  ] loop
    execute format('drop policy if exists "%s_select_autenticado" on public.%I', tbl, tbl);
    execute format(
      'create policy "%s_select_autenticado" on public.%I for select to authenticated using (private.has_active_profile((select auth.uid())))',
      tbl,
      tbl
    );
    execute format('comment on policy "%s_select_autenticado" on public.%I is %L', tbl, tbl, 'Catalogo de dominio disponivel para usuarios ativos.');
  end loop;

  foreach tbl in array array[
    'clientes', 'empresas', 'contratos', 'projetos', 'unidades_instaladas',
    'colaboradores', 'terceirizados', 'estoque_materiais', 'pendencias_padrao'
  ] loop
    execute format('drop policy if exists "%s_select_autenticado" on public.%I', tbl, tbl);
    execute format('drop policy if exists "%s_insert_gestor" on public.%I', tbl, tbl);
    execute format('drop policy if exists "%s_update_gestor" on public.%I', tbl, tbl);
    execute format(
      'create policy "%s_select_autenticado" on public.%I for select to authenticated using (private.has_active_profile((select auth.uid())))',
      tbl,
      tbl
    );
    execute format(
      'create policy "%s_insert_gestor" on public.%I for insert to authenticated with check (private.is_gestor((select auth.uid())))',
      tbl,
      tbl
    );
    execute format(
      'create policy "%s_update_gestor" on public.%I for update to authenticated using (private.is_gestor((select auth.uid()))) with check (private.is_gestor((select auth.uid())))',
      tbl,
      tbl
    );
    execute format('comment on policy "%s_select_autenticado" on public.%I is %L', tbl, tbl, 'Tecnico e gestor podem consultar cadastro base quando ativos.');
    execute format('comment on policy "%s_insert_gestor" on public.%I is %L', tbl, tbl, 'Somente gestor pode criar cadastro base.');
    execute format('comment on policy "%s_update_gestor" on public.%I is %L', tbl, tbl, 'Somente gestor pode alterar cadastro base, incluindo soft-delete via ativo=false.');
  end loop;
end $$;

drop policy if exists "ordens_manutencao_select_autenticado" on public.ordens_manutencao;
create policy "ordens_manutencao_select_autenticado"
on public.ordens_manutencao for select
to authenticated
using (private.has_active_profile((select auth.uid())));
comment on policy "ordens_manutencao_select_autenticado" on public.ordens_manutencao
  is 'Usuarios ativos consultam OS; escrita e limitada por policies separadas.';

drop policy if exists "ordens_manutencao_insert_autenticado" on public.ordens_manutencao;
create policy "ordens_manutencao_insert_autenticado"
on public.ordens_manutencao for insert
to authenticated
with check (
  private.has_active_profile((select auth.uid()))
  and criado_por = (select auth.uid())
);
comment on policy "ordens_manutencao_insert_autenticado" on public.ordens_manutencao
  is 'Tecnico e gestor ativos podem criar OS identificando o usuario criador.';

drop policy if exists "ordens_manutencao_update_gestor" on public.ordens_manutencao;
create policy "ordens_manutencao_update_gestor"
on public.ordens_manutencao for update
to authenticated
using (private.is_gestor((select auth.uid())))
with check (private.is_gestor((select auth.uid())));
comment on policy "ordens_manutencao_update_gestor" on public.ordens_manutencao
  is 'Somente gestor altera OS diretamente, inclusive cancelamento; status operacional e recalculado por trigger.';

drop policy if exists "pendencias_ordem_select_autenticado" on public.pendencias_ordem_manutencao;
create policy "pendencias_ordem_select_autenticado"
on public.pendencias_ordem_manutencao for select
to authenticated
using (private.has_active_profile((select auth.uid())));
comment on policy "pendencias_ordem_select_autenticado" on public.pendencias_ordem_manutencao
  is 'Usuarios ativos consultam pendencias de OS.';

drop policy if exists "pendencias_ordem_insert_autenticado" on public.pendencias_ordem_manutencao;
create policy "pendencias_ordem_insert_autenticado"
on public.pendencias_ordem_manutencao for insert
to authenticated
with check (
  private.has_active_profile((select auth.uid()))
  and exists (
    select 1
    from public.ordens_manutencao om
    where om.id_ordem = pendencias_ordem_manutencao.id_ordem
      and (om.criado_por = (select auth.uid()) or private.is_gestor((select auth.uid())))
  )
);
comment on policy "pendencias_ordem_insert_autenticado" on public.pendencias_ordem_manutencao
  is 'Pendencias podem ser adicionadas na criacao da OS pelo criador ou por gestor.';

drop policy if exists "pendencias_ordem_update_gestor" on public.pendencias_ordem_manutencao;
create policy "pendencias_ordem_update_gestor"
on public.pendencias_ordem_manutencao for update
to authenticated
using (private.is_gestor((select auth.uid())))
with check (private.is_gestor((select auth.uid())));
comment on policy "pendencias_ordem_update_gestor" on public.pendencias_ordem_manutencao
  is 'Alteracao direta da pendencia da OS e reservada ao gestor; atendimento usa atendimentos_executados.';

drop policy if exists "atendimentos_select_autenticado" on public.atendimentos_ordens;
create policy "atendimentos_select_autenticado"
on public.atendimentos_ordens for select
to authenticated
using (private.has_active_profile((select auth.uid())));
comment on policy "atendimentos_select_autenticado" on public.atendimentos_ordens
  is 'Usuarios ativos leem atendimentos operacionais.';

drop policy if exists "atendimentos_insert_autenticado" on public.atendimentos_ordens;
create policy "atendimentos_insert_autenticado"
on public.atendimentos_ordens for insert
to authenticated
with check (
  private.has_active_profile((select auth.uid()))
  and criado_por = (select auth.uid())
);
comment on policy "atendimentos_insert_autenticado" on public.atendimentos_ordens
  is 'Tecnico ou gestor ativo pode abrir atendimento, registrado como criador.';

drop policy if exists "atendimentos_update_participante_ou_gestor" on public.atendimentos_ordens;
create policy "atendimentos_update_participante_ou_gestor"
on public.atendimentos_ordens for update
to authenticated
using (
  private.is_gestor((select auth.uid()))
  or criado_por = (select auth.uid())
  or exists (
    select 1
    from public.equipes e
    where e.id_atendimento = atendimentos_ordens.id_atendimento
      and e.id_colaborador = private.current_id_colaborador()
  )
)
with check (
  private.is_gestor((select auth.uid()))
  or criado_por = (select auth.uid())
  or exists (
    select 1
    from public.equipes e
    where e.id_atendimento = atendimentos_ordens.id_atendimento
      and e.id_colaborador = private.current_id_colaborador()
  )
);
comment on policy "atendimentos_update_participante_ou_gestor" on public.atendimentos_ordens
  is 'Tecnico edita atendimento que abriu ou do qual participa; gestor edita todos.';

drop policy if exists "equipes_select_autenticado" on public.equipes;
create policy "equipes_select_autenticado"
on public.equipes for select
to authenticated
using (private.has_active_profile((select auth.uid())));
comment on policy "equipes_select_autenticado" on public.equipes
  is 'Usuarios ativos leem equipes dos atendimentos.';

drop policy if exists "equipes_insert_participante_ou_gestor" on public.equipes;
create policy "equipes_insert_participante_ou_gestor"
on public.equipes for insert
to authenticated
with check (
  private.is_gestor((select auth.uid()))
  or criado_por = (select auth.uid())
  or exists (
    select 1
    from public.atendimentos_ordens ao
    where ao.id_atendimento = equipes.id_atendimento
      and ao.criado_por = (select auth.uid())
  )
);
comment on policy "equipes_insert_participante_ou_gestor" on public.equipes
  is 'Criador do atendimento pode montar equipe; gestor pode gerenciar todas.';

drop policy if exists "equipes_update_participante_ou_gestor" on public.equipes;
create policy "equipes_update_participante_ou_gestor"
on public.equipes for update
to authenticated
using (
  private.is_gestor((select auth.uid()))
  or criado_por = (select auth.uid())
  or exists (
    select 1
    from public.atendimentos_ordens ao
    where ao.id_atendimento = equipes.id_atendimento
      and ao.criado_por = (select auth.uid())
  )
  or id_colaborador = private.current_id_colaborador()
)
with check (
  private.is_gestor((select auth.uid()))
  or criado_por = (select auth.uid())
  or exists (
    select 1
    from public.atendimentos_ordens ao
    where ao.id_atendimento = equipes.id_atendimento
      and ao.criado_por = (select auth.uid())
  )
  or id_colaborador = private.current_id_colaborador()
);
comment on policy "equipes_update_participante_ou_gestor" on public.equipes
  is 'Participante, criador do atendimento ou gestor pode editar equipe.';

drop policy if exists "atendimentos_executados_select_autenticado" on public.atendimentos_executados;
create policy "atendimentos_executados_select_autenticado"
on public.atendimentos_executados for select
to authenticated
using (private.has_active_profile((select auth.uid())));
comment on policy "atendimentos_executados_select_autenticado" on public.atendimentos_executados
  is 'Usuarios ativos leem execucoes de pendencias.';

drop policy if exists "atendimentos_executados_insert_participante_ou_gestor" on public.atendimentos_executados;
create policy "atendimentos_executados_insert_participante_ou_gestor"
on public.atendimentos_executados for insert
to authenticated
with check (
  private.is_gestor((select auth.uid()))
  or exists (
    select 1
    from public.atendimentos_ordens ao
    where ao.id_atendimento = atendimentos_executados.id_atendimento
      and ao.criado_por = (select auth.uid())
  )
  or exists (
    select 1
    from public.equipes e
    where e.id_atendimento = atendimentos_executados.id_atendimento
      and e.id_colaborador = private.current_id_colaborador()
  )
);
comment on policy "atendimentos_executados_insert_participante_ou_gestor" on public.atendimentos_executados
  is 'Criador ou participante do atendimento registra tratamento de pendencias; gestor registra todos.';

drop policy if exists "atendimentos_executados_update_participante_ou_gestor" on public.atendimentos_executados;
create policy "atendimentos_executados_update_participante_ou_gestor"
on public.atendimentos_executados for update
to authenticated
using (
  private.is_gestor((select auth.uid()))
  or exists (
    select 1
    from public.atendimentos_ordens ao
    where ao.id_atendimento = atendimentos_executados.id_atendimento
      and ao.criado_por = (select auth.uid())
  )
  or exists (
    select 1
    from public.equipes e
    where e.id_atendimento = atendimentos_executados.id_atendimento
      and e.id_colaborador = private.current_id_colaborador()
  )
)
with check (
  private.is_gestor((select auth.uid()))
  or exists (
    select 1
    from public.atendimentos_ordens ao
    where ao.id_atendimento = atendimentos_executados.id_atendimento
      and ao.criado_por = (select auth.uid())
  )
  or exists (
    select 1
    from public.equipes e
    where e.id_atendimento = atendimentos_executados.id_atendimento
      and e.id_colaborador = private.current_id_colaborador()
  )
);
comment on policy "atendimentos_executados_update_participante_ou_gestor" on public.atendimentos_executados
  is 'Criador ou participante atualiza execucao de pendencia; gestor atualiza todas.';

drop policy if exists "movimentacoes_select_autenticado" on public.movimentacoes;
create policy "movimentacoes_select_autenticado"
on public.movimentacoes for select
to authenticated
using (private.has_active_profile((select auth.uid())));
comment on policy "movimentacoes_select_autenticado" on public.movimentacoes
  is 'Usuarios ativos leem movimentacoes para rastreabilidade.';

drop policy if exists "movimentacoes_insert_autenticado" on public.movimentacoes;
create policy "movimentacoes_insert_autenticado"
on public.movimentacoes for insert
to authenticated
with check (
  private.has_active_profile((select auth.uid()))
  and criado_por = (select auth.uid())
);
comment on policy "movimentacoes_insert_autenticado" on public.movimentacoes
  is 'Tecnico ou gestor ativo cria movimentacao, mas itens controlam baixa por atendimento.';

drop policy if exists "movimentacoes_update_gestor" on public.movimentacoes;
create policy "movimentacoes_update_gestor"
on public.movimentacoes for update
to authenticated
using (private.is_gestor((select auth.uid())))
with check (private.is_gestor((select auth.uid())));
comment on policy "movimentacoes_update_gestor" on public.movimentacoes
  is 'Somente gestor altera cabecalho de movimentacao.';

drop policy if exists "movimentacoes_estoque_select_autenticado" on public.movimentacoes_estoque;
create policy "movimentacoes_estoque_select_autenticado"
on public.movimentacoes_estoque for select
to authenticated
using (private.has_active_profile((select auth.uid())));
comment on policy "movimentacoes_estoque_select_autenticado" on public.movimentacoes_estoque
  is 'Usuarios ativos leem itens de movimentacao de estoque.';

drop policy if exists "movimentacoes_estoque_insert_baixa_ou_gestor" on public.movimentacoes_estoque;
create policy "movimentacoes_estoque_insert_baixa_ou_gestor"
on public.movimentacoes_estoque for insert
to authenticated
with check (
  private.is_gestor((select auth.uid()))
  or (
    id_atendimento is not null
    and exists (
      select 1
      from public.movimentacoes m
      where m.id_movimentacao = movimentacoes_estoque.id_movimentacao
        and m.criado_por = (select auth.uid())
        and m.tipo_codigo = 'saida'
    )
    and (
      exists (
        select 1
        from public.atendimentos_ordens ao
        where ao.id_atendimento = movimentacoes_estoque.id_atendimento
          and ao.criado_por = (select auth.uid())
      )
      or exists (
        select 1
        from public.equipes e
        where e.id_atendimento = movimentacoes_estoque.id_atendimento
          and e.id_colaborador = private.current_id_colaborador()
      )
    )
  )
);
comment on policy "movimentacoes_estoque_insert_baixa_ou_gestor" on public.movimentacoes_estoque
  is 'Tecnico so baixa material via atendimento em que participa; gestor pode fazer ajustes completos.';

drop policy if exists "movimentacoes_estoque_update_gestor" on public.movimentacoes_estoque;
create policy "movimentacoes_estoque_update_gestor"
on public.movimentacoes_estoque for update
to authenticated
using (private.is_gestor((select auth.uid())))
with check (private.is_gestor((select auth.uid())));
comment on policy "movimentacoes_estoque_update_gestor" on public.movimentacoes_estoque
  is 'Somente gestor altera itens de movimentacao apos criacao.';

drop policy if exists "historico_unidade_select_gestor" on public.historico_unidade;
create policy "historico_unidade_select_gestor"
on public.historico_unidade for select
to authenticated
using (private.is_gestor((select auth.uid())));
comment on policy "historico_unidade_select_gestor" on public.historico_unidade
  is 'Historico tecnico consolidado fica restrito a gestor no MVP.';

drop policy if exists "historico_unidade_insert_gestor" on public.historico_unidade;
create policy "historico_unidade_insert_gestor"
on public.historico_unidade for insert
to authenticated
with check (private.is_gestor((select auth.uid())));
comment on policy "historico_unidade_insert_gestor" on public.historico_unidade
  is 'Somente gestor registra historico manual de unidade.';

drop policy if exists "notificacoes_select_gestor" on public.notificacoes;
create policy "notificacoes_select_gestor"
on public.notificacoes for select
to authenticated
using (private.is_gestor((select auth.uid())));
comment on policy "notificacoes_select_gestor" on public.notificacoes
  is 'Notificacoes ficam restritas a gestor no MVP.';

drop policy if exists "notificacoes_insert_gestor" on public.notificacoes;
create policy "notificacoes_insert_gestor"
on public.notificacoes for insert
to authenticated
with check (private.is_gestor((select auth.uid())));
comment on policy "notificacoes_insert_gestor" on public.notificacoes
  is 'Somente gestor cria notificacoes no MVP.';

-- Views do not support RLS policies; access is restricted by grants and the
-- view uses security_invoker so underlying table RLS still applies.
grant select on table public.vw_atendimentos_por_projeto to authenticated;
