create table if not exists public.unidades (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  cliente text not null,
  contrato text not null,
  projeto text not null,
  municipio text not null,
  status text not null default 'Instalada',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ordens (
  id bigint generated by default as identity primary key,
  unidade_id bigint not null references public.unidades(id) on delete restrict,
  protocolo text not null unique,
  tipo text not null,
  prioridade text not null check (prioridade in ('P1', 'P2', 'P3', 'P4')),
  status text not null check (status in ('Aberta', 'Agendada', 'Em atendimento', 'Pendente', 'Concluida')),
  abertura date not null default current_date,
  prazo_sla date not null,
  responsavel text not null default 'A definir',
  descricao text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pendencias_ordem (
  id bigint generated by default as identity primary key,
  ordem_id bigint not null references public.ordens(id) on delete cascade,
  descricao text not null,
  status text not null default 'Aberta',
  created_at timestamptz not null default now()
);

create table if not exists public.atendimentos (
  id bigint generated by default as identity primary key,
  ordem_id bigint not null references public.ordens(id) on delete restrict,
  data date not null default current_date,
  equipe text not null default 'Equipe interna',
  status text not null check (status in ('Executado', 'Parcial', 'Reagendado')),
  relato text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.atendimento_materiais (
  id bigint generated by default as identity primary key,
  atendimento_id bigint not null references public.atendimentos(id) on delete cascade,
  descricao text not null
);

create table if not exists public.estoque (
  id bigint generated by default as identity primary key,
  item text not null,
  categoria text not null,
  unidade text not null,
  quantidade numeric not null default 0,
  minimo numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_ordens_unidade_id on public.ordens(unidade_id);
create index if not exists idx_ordens_status on public.ordens(status);
create index if not exists idx_ordens_prazo_sla on public.ordens(prazo_sla);
create index if not exists idx_atendimentos_ordem_id on public.atendimentos(ordem_id);
create index if not exists idx_pendencias_ordem_id on public.pendencias_ordem(ordem_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_unidades_updated_at on public.unidades;
create trigger set_unidades_updated_at
before update on public.unidades
for each row execute function public.set_updated_at();

drop trigger if exists set_ordens_updated_at on public.ordens;
create trigger set_ordens_updated_at
before update on public.ordens
for each row execute function public.set_updated_at();

drop trigger if exists set_estoque_updated_at on public.estoque;
create trigger set_estoque_updated_at
before update on public.estoque
for each row execute function public.set_updated_at();

alter table public.unidades enable row level security;
alter table public.ordens enable row level security;
alter table public.pendencias_ordem enable row level security;
alter table public.atendimentos enable row level security;
alter table public.atendimento_materiais enable row level security;
alter table public.estoque enable row level security;

drop policy if exists "service role full access unidades" on public.unidades;
create policy "service role full access unidades" on public.unidades
for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

drop policy if exists "service role full access ordens" on public.ordens;
create policy "service role full access ordens" on public.ordens
for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

drop policy if exists "service role full access pendencias_ordem" on public.pendencias_ordem;
create policy "service role full access pendencias_ordem" on public.pendencias_ordem
for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

drop policy if exists "service role full access atendimentos" on public.atendimentos;
create policy "service role full access atendimentos" on public.atendimentos
for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

drop policy if exists "service role full access atendimento_materiais" on public.atendimento_materiais;
create policy "service role full access atendimento_materiais" on public.atendimento_materiais
for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

drop policy if exists "service role full access estoque" on public.estoque;
create policy "service role full access estoque" on public.estoque
for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
